apiVersion: v1
kind: Service
metadata:
  name: image-api
spec:
  selector:
    api: image
  ports:
    - protocol: TCP
      port: 3020
      name: image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-api
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      api: image
  template:
    metadata:
      labels:
        api: image
    spec:
#      initContainers:
#        - name: wait-for-rabbit
#          imagePullPolicy: IfNotPresent
#          image: busybox:1.36.0
#          command:
#            [
#              "sh",
#              "-c",
#              "until nc -vz rabbit.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5672; do echo waiting for rabbit; sleep 2; done",
#            ]
      containers:
        - name: image-api
          image: jym272/image-api:ska
#          securityContext:
#            seccompProfile:
#              type: RuntimeDefault
#            capabilities:
#              drop: [ "NET_RAW" ]
#            readOnlyRootFilesystem: true
#            allowPrivilegeEscalation: false
#            runAsNonRoot: true
#            runAsUser: 10001
#            runAsGroup: 10000
#          readinessProbe:
#            httpGet:
#              path: /api/healthz  # /api/healthz -> connection to rabbitmq
#              port: 3020
#            periodSeconds: 5
#            failureThreshold: 1
#          livenessProbe:
#            httpGet:
#              path: /health  # /api/healthz
#              port: 3020
#            periodSeconds: 10
#            failureThreshold: 2
#          startupProbe:
#            httpGet:
#              path: /health
#              port: 3020
#            failureThreshold: 30
#            periodSeconds: 1
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: FORCE_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FORCE_COLOR
            - name: NACK_DELAY_MS
              value: "2000"
            - name: NACK_MAX_RETRIES
              value: "15"
            - name: RABBIT_SERVER_HOST
              value: nats.default.svc.cluster.local
            - name: RABBIT_SERVER_PORT
              value: "5672"
            - name: PORT
              value: "3020"
            - name: RABBITMQ_DEFAULT_USER
              value: rabbit
            - name: RABBITMQ_DEFAULT_PASS
              value: "1234"
